### ISSUE TITLE
NullpointerException in GenericQuartzJob

### ISSUE THREAD

**Issue by stanmine** [xenit-eu/dynamic-extensions-for-alfresco#156]
When uploading a bundle, a nullpointer exception occurres in the GenericQuartzJob class.

Stacktrace:
```
[ALFRESCO] 2017-10-10 12:06:45,002  ERROR [quartz.core.JobRunShell] [DefaultScheduler_Worker-8] Job Monitoring.ClusteringMetric threw an unhandled Exception:
 java.lang.NullPointerException
        at com.github.dynamicextensionsalfresco.quartz.GenericQuartzJob.execute(GenericQuartzJob.java:16)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
[ALFRESCO] 2017-10-10 12:06:45,002  ERROR [quartz.core.ErrorLogger] [DefaultScheduler_Worker-8] Job (Monitoring.ClusteringMetric threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:227)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
Caused by: java.lang.NullPointerException
        at com.github.dynamicextensionsalfresco.quartz.GenericQuartzJob.execute(GenericQuartzJob.java:16)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        ... 1 more
```

**Comment by tgeens** [comment]
Looks like a null-pointer in new (?) code from PR #145 "Add lock support to scheduled jobs"

@stanmine Just revert that merge
