### ISSUE TITLE
Unable to install bundle that doesn't export any packages

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/dynamic-extensions-for-alfresco#246]
## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior
I am able to install a bundle that doesn't export any packages through the 'Export-Package' MANIFEST header.

## Current Behavior
When a bundle that doesn't export any packages is installed, following ERROR is in the logs:
```
 2019-05-14 06:26:55,640  ERROR [internal.support.ExtenderConfiguration] [http-nio-8080-exec-26] Application context refresh failed (DynamicExtensionsApplicationContext(bundle=example-dynamic-extension, config=osgibundle:/META-INF/spring/*.xml))
 java.lang.IllegalArgumentException: At least one base package must be specified
	at org.springframework.util.Assert.notEmpty(Assert.java:361)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:272)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:253)
	at com.github.dynamicextensionsalfresco.blueprint.DynamicExtensionsApplicationContext.scanPackages(DynamicExtensionsApplicationContext.java:203)
```
And it looks like the bundle is not correctly installed, although it is marked `ACTIVE` in the control-panel.

## Possible Solution
If no 'Export-Package' are defined, do not scan any packages at this point:
```
com.github.dynamicextensionsalfresco.blueprint.DynamicExtensionsApplicationContext.scanPackages(DynamicExtensionsApplicationContext.java:203)
```

## Steps to Reproduce (for bugs)
1. Install a bundle that doesn't export any packages.

## Your Environment
* Alfresco version used: 5.2.4
* DE version used: 1.7.6

Also reproducible in current master branch, DE 2.0.0-SNAPSHOT, Alfresco 6.1

**Comment by kerkhofsd** [comment]
The merged fix for this issue, which causes a small change in behavior of Dynamic Extensions bean loading, causes issues. 

Change in behavior:
Before the PR changes, only the packages present in the `Export-Package` header were scanned for beans. 
After the PR changes, all the packages inside the bundle are scanned for beans. 

This causes issues in bundles that for some reason contained beans in not exported packages. E.g. in bundles embedding other dependencies, unexpected beans can be loaded because the embedded dependencies are also scanned. 

Therefore I will revert this change & keep the behavior like it was.
