### ISSUE TITLE
Alfresco startup fails with version 7.3

### ISSUE THREAD

**Issue by panzerj** [xenit-eu/dynamic-extensions-for-alfresco#361]
When I try to start Alfresco 7.3 with the latest Alfresco Dynamic Extensions module, I get the following error message. My own extensions are not loaded. The Error exists if I only load dynamic extentions module (without my own extension)

INFO  [repo.module.ModuleServiceImpl] [main] Installing module 'alfresco-dynamic-extensions-repo' version 3.0.0.
  2022-12-13 07:19:13,896  ERROR [dynamicextensionsalfresco.osgi.DefaultFrameworkManager] [main] Error starting bundle org.eclipse.gemini.blueprint.extender:
  org.osgi.framework.BundleException: Activator start error in bundle org.eclipse.gemini.blueprint.extender [1].
     at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
     at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
     at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
     at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
     at com.github.dynamicextensionsalfresco.osgi.DefaultFrameworkManager.startBundle(DefaultFrameworkManager.java:209)
     at com.github.dynamicextensionsalfresco.osgi.DefaultFrameworkManager.startBundles(DefaultFrameworkManager.java:201)
     at com.github.dynamicextensionsalfresco.osgi.DefaultFrameworkManager.initialize(DefaultFrameworkManager.java:93)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeCustomInitMethod$7(AbstractAutowireCapableBeanFactory.java:1920)
     at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1919)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
     at com.github.dynamicextensionsalfresco.osgi.OsgiContainerModuleComponent.initializeOsgiContainerApplicationContext(OsgiContainerModuleComponent.java:113)
     at com.github.dynamicextensionsalfresco.osgi.OsgiContainerModuleComponent.startFramework(OsgiContainerModuleComponent.java:100)
     at com.github.dynamicextensionsalfresco.osgi.OsgiContainerModuleComponent.executeInternal(OsgiContainerModuleComponent.java:60)
     at org.alfresco.repo.module.AbstractModuleComponent.execute(AbstractModuleComponent.java:361)
     at org.alfresco.repo.module.ModuleComponentHelper.executeComponent(ModuleComponentHelper.java:736)
     at org.alfresco.repo.module.ModuleComponentHelper.startModule(ModuleComponentHelper.java:647)
     at org.alfresco.repo.module.ModuleComponentHelper.startModule(ModuleComponentHelper.java:576)
     at org.alfresco.repo.module.ModuleComponentHelper.access$5(ModuleComponentHelper.java:530)
     at org.alfresco.repo.module.ModuleComponentHelper$1$1.execute(ModuleComponentHelper.java:263)
     at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:452)
     at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:340)
     at org.alfresco.repo.module.ModuleComponentHelper$1.doWork(ModuleComponentHelper.java:284)
     at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
     at org.alfresco.repo.module.ModuleComponentHelper.startModules(ModuleComponentHelper.java:213)
     at org.alfresco.repo.module.ModuleServiceImpl.startModules(ModuleServiceImpl.java:149)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
     at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
     at jdk.proxy3/jdk.proxy3.$Proxy127.startModules(Unknown Source)
     at org.alfresco.repo.module.ModuleStarter$1.execute(ModuleStarter.java:73)
     at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:452)
     at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:340)
     at org.alfresco.repo.module.ModuleStarter$2.doWork(ModuleStarter.java:83)
     at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
     at org.alfresco.repo.module.ModuleStarter.onBootstrap(ModuleStarter.java:78)
     at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
     at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:232)
     at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:197)
     at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:217)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
     at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
     at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
     at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)
     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
     at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
     at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:149)
     at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:139)
     at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:696)
     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
     at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1185)
     at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1933)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
     at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1095)
     at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:477)
     at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
     at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
     at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
     at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
     at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
     at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
     at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
 Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from OSGi resource[bundle://95dc25c7-523e-4b7d-9894-586417002972_2.0:0/META-INF/spring/extender/extender-context.xml|bnd.id=1|bnd.sym=org.eclipse.gemini.blueprint.extender]; nested exception is java.net.MalformedURLException: unknown protocol: bundle
     at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342)
     at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310)
     at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:196)
     at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:232)
     at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:203)
     at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:171)
     at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:141)
     at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
     at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671)
     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
     at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$301(AbstractDelegatedExecutionApplicationContext.java:57)
     at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$1.run(AbstractDelegatedExecutionApplicationContext.java:165)
     at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
     at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.normalRefresh(AbstractDelegatedExecutionApplicationContext.java:161)
     at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$NoDependenciesWaitRefreshExecutor.refresh(AbstractDelegatedExecutionApplicationContext.java:75)
     at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
     at org.eclipse.gemini.blueprint.extender.internal.support.ExtenderConfiguration.start(ExtenderConfiguration.java:164)
     at org.eclipse.gemini.blueprint.extender.internal.boot.ChainActivator.start(ChainActivator.java:93)
     at org.apache.felix.framework.util.SecureAction$Actions.run(SecureAction.java:1786)
     at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
     at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:689)
     at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
     ... 115 more
 Caused by: java.net.MalformedURLException: unknown protocol: bundle
     at java.base/java.net.URL.<init>(URL.java:681)
     at java.base/java.net.URL.<init>(URL.java:569)
     at java.base/java.net.URL.<init>(URL.java:516)
     at org.eclipse.gemini.blueprint.io.OsgiBundleResource.getURL(OsgiBundleResource.java:220)
     at org.eclipse.gemini.blueprint.io.OsgiBundleResource.getInputStream(OsgiBundleResource.java:181)
     at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:333)
     ... 136 more

**Comment by FlexSolution** [comment]
Probably java17 causes the issue. We had the same issue but after downgrading java to version 11 everything works as expected

**Comment by tongchaij** [comment]
Change org.apache.felix.framework-6.0.5.jar to org.apache.felix.framework-7.0.5.jar

**Comment by panzerj** [comment]
@tongchaij that seems to solve my problem
